### ISSUE TITLE
tan(90°)

### ISSUE THREAD

**Issue by 70CentsApple** [Emirlol/chatcalc#3]
`tan(90)` should return `∞`, as `1/0` does.

~~Perhaps a special judge would be enough.~~

Edit: it can also reproduce for `tan(0.5*pirad)` or something like that.
One possible solution I could find out is that when calculating `tan(x)`, consider it be zero when the value `cos(x)` is small enough.

Edit 2:
```java
import java.math.*;
public class Main {
    public static void main(String args[]) throws Exception {
        System.out.println(Math.cos(Math.toRadians(90)));
    }
}
```
I tested this code, and it gives me `6.123233995736766E-17`, which is `0.0000000000000000612323`.
I think comparing `cos(x)` value with `0.0000000000000001` which is `1E-16` is surely enough to tell if the `cos(x)` value should be consider as zero.

Adding that custom `tan()` function here would be nice.
https://github.com/Emirlol/chatcalc/blob/a1513b5dcd1bc9995a77da3bd40152e736a66038/src/main/kotlin/ca/rttv/chatcalc/MathematicalFunction.kt#L22
https://github.com/Emirlol/chatcalc/blob/a1513b5dcd1bc9995a77da3bd40152e736a66038/src/main/kotlin/ca/rttv/chatcalc/MathematicalFunction.kt#L25

**Comment by RealRTTV** [comment]
tan(`90deg`)
