### ISSUE TITLE
Listing saved functions crashes the game if there are no functions saved

### ISSUE THREAD

**Issue by SnipUndercover** [Emirlol/chatcalc#6]
Self-explanatory. Entering `functions?` into the chat and pressing <kbd>Tab</kbd> crashes the game if there are no functions defined.

```
Caused by: java.lang.UnsupportedOperationException: Empty sequence can't be reduced.
	at ca.rttv.chatcalc.ChatCalc.tryParse(ChatCalc.kt:155)
```

I assume entering `constants?` also crashes the game if there are no constants defined, however I haven't tested it.

**Comment by Emirlol** [comment]
Thank you for the issues.
